# Generated by Django 5.2.3 on 2025-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('review', models.TextField(verbose_name='Отзыв о фильме')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
